"""initial migration

Revision ID: 2e8b45f2b32
Revises: None
Create Date: 2016-01-19 18:11:31.032128

"""

# revision identifiers, used by Alembic.
revision = '2e8b45f2b32'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wxid', sa.String(length=64), nullable=False),
    sa.Column('stuid', sa.Integer(), nullable=False),
    sa.Column('pswd', sa.String(length=64), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_wxid', 'users', ['wxid'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_wxid', 'users')
    op.drop_table('users')
    op.drop_table('schools')
    ### end Alembic commands ###
